
## archivos provienen de AFO
ventas:
  columns:
    cod_cliente: str
    nombre_cliente: str
    cod_agente: str
    cod_oficina: str
    nombre_oficina: str
    cod_canal_dist: str
    nombre_canal_dist: str
    cod_sub_canal: str
    nombre_sub_canal_dist: str
  
costo_merc_vend:
  columns:
    cod_oficina : str
    nombre_oficina : str
    cod_ramo: str
    ramo: str
    ingresos_totales: float
    importe_moneda_grupo: float
    untilidad_no_realizada: float

facturas:
  columns:
    cod_cliente: str
    cod_agente: str
    num_facturas_acum: int64

### ARCHIVOS PROVENIENTES DE EXCEL
gastos:
  usecols:
    "C,G,H,J,L,M" # string con las columnas que se van a utilizar Cod.of, Cod_sub_canal, Importe, des_agrupa_costo
  names:
    - cod_oficina
    - tipo_gasto
    - cod_sub_canal
    - gasto
    - modelo_atencion
    - agrupacion_costo
  sheet_name: 
    Hoja1
  dtype:
    cod_oficina : str
    cod_sub_canal : str
    gasto : float
    modelo_atencion : str
    agrupacion_costo : str

    
universo_directa:
  usecols:
    "B,W,AA" # string con las columnas que se van a utilizar para la maestras de clientes directa
  names:
    - cod_cliente
    - funcion_in
    - cod_visitas
  sheet_name:
    Clientes_Activos_AGCO
    
universo_indirecta:
  usecols:
    "B,D,R,S" # string con las columnas que se van a utilizar para la maestras de clientes directa
  names:
    - cod_agente
    - cod_vendedor
    - cod_visitas
    - cod_cliente
  sheet_name: 
    Hoja1

costo_por_minuto:
  usecols:
    "D,F,I,J,K"
  names:
    - cod_oficina
    - modelo_atencion
    - num_vendedores
    - tiempo_promedio_atencion
    - tiempo_promedio_entre_clientes
  sheet_name:
    costo_x_minuto_visita
  dtype:
    cod_oficina: str
    modelo_atencion: str
    num_vendedores: float
    tiempo_promedio_atencion: float
    tiempo_promedio_entre_clientes: float

costo_minuto_x_entrega:
  usecols:
    "A,B,C"
  names:
    - cod_oficina
    - nueva_segmentacion
    - tiempo_entrega
  sheet_name:
    costo_minuto_entrega
  dtype:
    cod_oficina: str
    nueva_segmentacion: str
    tiempo_entrega: float

##-------------------------------------------------------------------||----------------------------------------------###
###---------------------------- filtros--------------------------------###
##-------------------------------------------------------------------||----------------------------------------------###
filtros_func_in: # valores de los vendedores y jefes de ventas
  - 'Z1'
  - 'ZA'
  - 'Z6'

#filtros archivo ventas:
filtros_archivo_ventas:
    filtros_excluir:
      cod_oficina: ['00']

#filtros Modelo antencion
filtros:
  directa:
    modelo_atencion: 'Directa'
  indirecta:
    modelo_atencion: 'Indirecta'


### filtros archivos gastos por otros
gastos_por_otros:  
  directa:
    filtros_excluir:
      cod_oficina : ['10', '0','00']
      cod_sub_canal : ['CC']       
    filtros_incluir:
      agrupacion_costo : ['Costo por otros']
      modelo_atencion : ['Directa'] 
  indirecta:
    filtros_excluir:
      cod_oficina : ['10', '0','00']
      cod_sub_canal : ['CC']          
    filtros_incluir:
      agrupacion_costo : ['Costo por otros']
      modelo_atencion : ['Indirecta']

# filtros por gastos por visita
gastos_visita:
  filtros_excluir:
    cod_oficina : ['10', '0','00']
    cod_sub_canal : ['CC']          
  filtros_incluir:
    agrupacion_costo : ['Costo por visita']

# filtros por gastos por entrega fijos

gastos_entrega_fijos:
  directa:
    filtros_excluir:
      cod_oficina : ['10', '0','00']
      cod_sub_canal : ['CC']       
    filtros_incluir:
      agrupacion_costo : ['Costo por entrega']
      modelo_atencion : ['Directa'] 
      tipo_gasto: ['Fijo']
  indirecta:
    filtros_excluir:
      cod_oficina : ['10', '0','00']
      cod_sub_canal : ['CC']
    filtros_incluir:
      agrupacion_costo : ['Costo por entrega']
      modelo_atencion : ['Indirecta']
      tipo_gasto: ['Fijo']

# filtros por gastos por entrega variable
gastos_entrega_variable:
  directa:
    filtros_excluir:
      cod_oficina : ['10', '0','00']
      cod_sub_canal : ['CC']       
    filtros_incluir:
      agrupacion_costo : ['Costo por entrega']
      modelo_atencion : ['Directa'] 
      tipo_gasto: ['Variable']
  indirecta: 
    filtros_excluir:
      cod_oficina : ['10', '0','00']
      cod_sub_canal : ['CC']
    filtros_incluir:
      agrupacion_costo : ['Costo por entrega']
      modelo_atencion : ['Indirecta']
      tipo_gasto: ['Variable']




##-------------------------------------------------------------------||----------------------------------------------###
###---------------------------- relaciones--------------------------------###
##-------------------------------------------------------------------||----------------------------------------------###
merge_cxm:
  left_on: ['cod_oficina','modelo_atencion']
  right_on: ['cod_oficina','modelo_atencion']

union_cxo:
  directa: ['cod_oficina','cod_sub_canal','modelo_atencion']
  indirecta: ['cod_oficina','modelo_atencion']

union_gasto_visita: ['cod_oficina','modelo_atencion']

merge_cxe:
  left_on: ['cod_oficina','nueva_segmentacion']
  right_on: ['cod_oficina','nueva_segmentacion']

##-------------------------------------------------------------------||----------------------------------------------###
###---------------------------- agrupaciones--------------------------------###
##-------------------------------------------------------------------||----------------------------------------------###

agrupa_vta_gxotro:
  directa:
    categorias: ['cod_oficina','cod_sub_canal','modelo_atencion']
    numericas: ['ventas_acumuladas']
  indirecta:
    categorias: ['cod_oficina','modelo_atencion']
    numericas: ['ventas_acumuladas']

agrupa_gastos:
  directa:
    categorias: ['cod_oficina','cod_sub_canal','modelo_atencion']
    numericas: ['gasto']
  indirecta:
    categorias: ['cod_oficina','modelo_atencion']
    numericas: ['gasto']

agrupa_gastos_visita: 
  categorias: ['cod_oficina','modelo_atencion']
  numericas: ['gasto']

##-------------------------------------------------------------------||----------------------------------------------###
###------------------------------------- Drivers para nueva segmentación------------------###
##-------------------------------------------------------------------||----------------------------------------------###
prioridad:
  - condicion: "modelo_atencion == 'Indirecta'"
    asignar: "I"
  - condicion: "cod_sub_canal == 'CR'"
    asignar: "CR"
  - condicion: "cod_sub_canal == 'MY'"
    asignar: "AM"
  - condicion: "cod_canal=='T'"
    asignar: "TI"
default: "AM"

##-------------------------------------------------------------------||----------------------------------------------###
###------------------------------------- Formulas------------------###
##-------------------------------------------------------------------||----------------------------------------------###
columnas_calculadas:
  cogs_anual :  porc_cogs * ventas_acumuladas
  cogs_mensual : cogs_anual / conteo_meses
  utilidad_bruta_anual: ventas_acumuladas - cogs_anual
  utilidad_bruta_mensual : ventas_promedio - cogs_mensual
  gas_x_otros_anual: porc_costo_x_otros * ventas_acumuladas
  gas_x_otros_mensual:  porc_costo_x_otros * ventas_promedio
  utilidad_operativa_anual: utilidad_bruta_anual - gas_x_otros_anual
  utilidad_operativa_mensual : utilidad_bruta_mensual - gas_x_otros_mensual
  visitas_x_mes:  num_visita_semana * 4.33
  minutos_por_anio: 7*60*5*4.33*total_meses_analizado 
  minutos_totales : tiempo_promedio_atencion+ tiempo_promedio_entre_clientes
  costo_x_minuto : gasto_sum / num_vendedores / minutos_por_anio
  costo_visita: costo_x_minuto*minutos_totales*visitas_x_mes
  costo_fijo_entrega: ventas_acumuladas*porc_costo_fijo_entrega

##-------------------------------------------------------------------||----------------------------------------------###
###------------------------------------- columnas borrar------------------###
##-------------------------------------------------------------------||----------------------------------------------###
columnas_borrar:
  - porc_cogs
  - porc_costo_x_otros
  - cod_ramo
  - tiempo_promedio_atencion
  - tiempo_promedio_entre_clientes
  - gasto_sum
  - num_vendedores
  - minutos_por_anio
  - porc_costo_fijo_entrega
